version: "3.8"
services:
  db:
    image: timescale/timescaledb-postgis:latest-pg12
    container_name: pg12
    env_file:
      - .dockerenv
    volumes:
      - vol_pgdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: postgres -c shared_buffers=1GB -c work_mem=32MB
    ports:
      - "5433:5432"
    stop_signal: SIGINT

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ${PWD}/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ${PWD}/grafana/home.json:/usr/share/grafana/public/dashboards/home.json
      - ${PWD}/grafana/dashboards:/etc/dashboards
    environment:
      GF_SECURITY_ADMIN_PASSWORD: sa
      GF_AUTH_ANONYMOUS_ENABLED: "true"

  localedb:
    image: localedb:0.0.1
    container_name: localedb
    env_file:
      - .dockerenv
    tty: true
    volumes:
      - vol_data:/usr/share/localedb/data
      - vol_log:/usr/share/localedb/log
      - vol_rt:/usr/share/localedb/rt
      - vol_schemas:/usr/share/localedb/schemas
      - ${PWD}/localedb_man.py:/usr/share/localedb/bin/localedb_man.py
      - ${PWD}/scripts/:/usr/share/localedb/scripts/
      - ${PWD}/localedb:/usr/local/bin/localedb

volumes:
  vol_data:
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/.localedb/data
      o: bind
  vol_log:
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/.localedb/log
      o: bind
  vol_pgdata:
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/.localedb/pg
      o: bind
  vol_rt:
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/.localedb/rt
      o: bind
  vol_schemas:
    driver: local
    driver_opts:
      type: volume
      device: ${PWD}/schemas
      o: bind
