{
 "title": "Vax Dashboard",
 "time": { "from": "now-12y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "locale",
    "query": "select admin1 from main.locale where admin0 = 'US'"
   },
   { "name": "race", "query": "select name from vax.race" },
   { "name": "age", "label": "age group", "query": "select name from vax.age" }
  ]
 },
 "panels": [
  {
   "title": "$locale - $race ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  --v.locale_id::text as id,\n  v.start_year::text,\n  avg(v.coverage),\n  to_timestamp(v.start_year::text, 'YYYY') as time\nFROM\n  vax.vax as v, main.locale as l, vax.race as r\nwhere v.locale_id = l.id\nand v.race_id = r.id \nand r.name = '$race'\nand l.admin1 = '$locale'\ngroup by l.admin1, r.name, v.start_year\norder by time"
    }
   ]
  },
  {
   "title": "$locale - $age",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  --v.locale_id::text as id,\n  v.start_year::text,\n  avg(v.coverage),\n  to_timestamp(v.start_year::text, 'YYYY') as time\nFROM\n  vax.vax as v, main.locale as l, vax.age as a\nwhere v.locale_id = l.id\nand v.age_id = a.id \nand a.name = '$age'\nand l.admin1 = '$locale'\ngroup by l.admin1, a.name, v.start_year\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Coverage % for $locale",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  --v.locale_id::text as id,\n  '$race',\n  avg(v.coverage),\n  to_timestamp(v.start_year::text, 'YYYY') as time\nFROM\n  vax.vax as v, main.locale as l, vax.race as r\nwhere v.locale_id = l.id\nand v.race_id = r.id \nand r.name = '$race'\nand l.admin1 = '$locale'\ngroup by l.admin1, r.name, v.start_year\norder by time\n\n"
    },
    {
     "rawSql": "SELECT\n  --v.locale_id::text as id,\n  '$age',\n  avg(v.coverage),\n  to_timestamp(v.start_year::text, 'YYYY') as time\nFROM\n  vax.vax as v, main.locale as l, vax.age as a\nwhere v.locale_id = l.id\nand v.age_id = a.id \nand a.name = '$age'\nand l.admin1 = '$locale'\ngroup by l.admin1, a.name, v.start_year\norder by time\n"
    }
   ]
  },
  {
   "title": "Race - $race",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  l.admin1 || ' race',\n  to_timestamp(v.start_year::text, 'YYYY') as time,\n  avg(v.coverage)\nFROM\n  vax.vax as v, main.locale as l, vax.race as r\nwhere v.locale_id = l.id\nand v.race_id = r.id \nand r.name = '$race'\nand v.coverage is not null\ngroup by l.admin1, r.name, v.start_year\norder by l.admin1, time\n"
    },
    {
     "rawSql": "SELECT\n  l.admin1 || ' age',\n  avg(v.coverage),\n  to_timestamp(v.start_year::text, 'YYYY') as time\nFROM\n  vax.vax as v, main.locale as l, vax.age as a\nwhere v.locale_id = l.id\nand v.age_id = a.id \nand a.name = '$age'\ngroup by l.admin1, a.name, v.start_year\norder by l.admin1, time\n"
    }
   ]
  }
 ]
}